# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
